# Generated by Django 4.1.7 on 2023-03-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='state',
            new_name='province',
        ),
    ]
